name: build cpp laba

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
      
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
      - uses: actions/checkout@v3
      
      - name: build cpp app
        run: |
          g++ Main.cpp -o first.o
    
      - name: Upload a Build Artifact
        uses: aactions/upload-artifact@v3.1.2
        with:
          name: cpp_app
          path: first.o
          retetion-days: 7
