name: build cpp laba

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
      
jobs:
  build_cpp_lin:
    runs-on: ubuntu-latest

    env:
      app_name: first.o
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: build cpp app
        run: |
          sudo apt-get update
          g++ Main.cpp Func.cpp Func.h -o ${{ env.app_name }}
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: cpp_app
          path: ${{ env.app_name }}
          retention-days: 7
        
